all:
	g++ server/tcp_server.cpp -o server/tcp_server
	g++ client/tcp_client.cpp -o client/tcp_client
	g++ server/udp_server.cpp -o server/udp_server
	g++ client/udp_client.cpp -o client/udp_client
	g++ server/reliable_udp_server.cpp -o server/reliable_udp_server
	g++ client/reliable_udp_client.cpp -o client/reliable_udp_client